name: Update Schedule

on:
  schedule:
    - cron: '0 22 * * *' # 每天北京时间早上 6 点自动运行
  workflow_dispatch:      # 支持手动触发运行

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Update IPTV
        run: |
          pipenv run dev
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # 确保 output 文件夹存在
          mkdir -p output
          # 将生成的所有结果添加到仓库
          git add output/*
          # 只有在有变化时才提交，防止报错
          git commit -m "自动更新直播源: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push
